
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Puns').del()
    .then(function () {
      // Inserts seed entries
      return knex('Puns').insert([
        {Pun: "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink."},
        {Pun: "Have you ever tried to eat a clock? It's very time consuming."},
        {Pun: "I'm reading a book about anti-gravity. It's impossible to put down."},
        {Pun: "The experienced carpenter really nailed it, but the new guy screwed everything up."},
        {Pun: "If there was someone selling drugs in this place, weed know."},
        {Pun: "When notes get in treble, bass-ically they get put behind bars. The alto-nate punishment is to push them off a clef and hope they land flat on sharp objects."},
        {Pun: "Why don't programmers like nature? It has too many bugs."},
        {Pun: "A man just assaulted me with milk, cream and butter. How dairy."},
        {Pun: "	A prisoner's favorite punctuation mark is the period. It marks the end of his sentence."},
        {Pun: "He drove his expensive car into a tree and found out how the Mercedes bends."},
        {Pun: "I used to be a banker but I lost interest."},
        {Pun: "I don't trust these stairs because they're always up to something."},
        {Pun: "It's not that the man did not know how to juggle, he just didn't have the balls to do it."},
        {Pun: "So what if I don't know what apocalypse means!? It's not the end of the world!"},
        {Pun: "When William joined the army he disliked the phrase 'fire at will'."},
        {Pun: "I relish the fact that you've mustard the strength to ketchup to me."},
        {Pun: "The one who invented the door knocker got a No-bell prize."},
        {Pun: "Why don't some couples go to the gym? Because some relationships don't work out."},
        {Pun: "Did you hear about the guy whose whole left side was cut off? He's all right now."},
        {Pun: "Claustrophobic people are more productive thinking outside the box."},
        {Pun: "The shoemaker did not deny his apprentice anything he needed. He gave his awl."},
        {Pun: "A new type of broom came out, it is sweeping the nation."},
        {Pun: "I like European food so I decided to Russia over there because I was Hungary. After Czech'ing the menu I ordered Turkey. When I was Finnished I told the waiter 'Spain good but there is Norway I could eat another bite'."},
        {Pun: "I once got into so much debt that I couldn't even afford my electricity bills, they were the darkest times of my life."},
        {Pun: "What is the difference between a nicely dressed man on a tricycle and a poorly dressed man on a bicycle? A tire."},
        {Pun: "I once heard a joke about amnesia, but I forgot how it goes."},
        {Pun: "The roundest knight at king Arthur's round table was Sir Cumference."},
        {Pun: "A bicycle can't stand on its own because it is two-tired."},
        {Pun: "I'm glad I know sign language, it's pretty handy."},
        {Pun: "Need an ark to save two of every animal? I noah guy."},
        {Pun: "Police were called to a daycare where a three-year-old was resisting a rest."},
        {Pun: "My friend's bakery burned down last night. Now his business is toast."},
        {Pun: "A small boy swallowed some coins and was taken to a hospital. When his grandmother telephoned to ask how he was a nurse said 'No change yet'."},
        {Pun: "What did the grape say when it got stepped on? Nothing - but it let out a little whine."},
        {Pun: "The girl quit her job at the doughnut factory because she was fed up with the hole business."},
        {Pun: "When Peter Pan punches, they Neverland."},
        {Pun: "The man who survived mustard gas and pepper spray is now a seasoned veteran."},
        {Pun: "To write with a broken pencil is pointless."},
        {Pun: "There was once a cross-eyed teacher who couldn't control his pupils."},
        {Pun: "The other day I held the door open for a clown. I thought it was a nice jester."},
        {Pun: "I was going to look for my missing watch, but I could never find the time."},
        {Pun: "I think Santa has riverfront property in Brazil. All our presents came from Amazon this year."},
        {Pun: "I knew a woman who owned a taser, man was she stunning!"},
        {Pun: "I did a theatrical performance about puns. Really it was just a play on words."},
        {Pun: "Is old rope good enough for a hanging? Frayed knot. That stuff is bad noose."},
        {Pun: "It was an emotional wedding. Even the cake was in tiers."},
        {Pun: "There was a sign on the lawn at a drug re-hab center that said 'Keep off the Grass'."},
        {Pun: "What do dogs do after they finish obedience school? They get their masters."},
        {Pun: "I used to have a fear of hurdles, but I got over it."},
        {Pun: "Atheism is a non-prophet organization."},
        {Pun: "Atheists don't solve exponential equations because they don't believe in higher powers."},
        {Pun: "The butcher backed up into the meat grinder and got a little behind in his work."},
        {Pun: "I saw a beaver movie last night, it was the best dam movie I've ever seen."},
        {Pun: "It's a lengthy article on Japanese Sword Fighters but I can Samurais it for you."},
        {Pun: "I went to the dentist without lunch, and he gave me a plate."},
        {Pun: "Two hats were hanging on a hat rack in the hallway. One hat says to the other, 'You stay here, I'll go on a head.'"},
        {Pun: "I don't get people who stumble into mirrors. They need to watch themselves."},
        {Pun: "There is a special species of bird that is really good at holding stuff together. They are called velcrows."},
        {Pun: "When the window fell into the incinerator, it was a pane in the ash to retrieve."},
        {Pun: "I really wanted a camouflage shirt, but I couldn't find one."},
        {Pun: "The first time I used an elevator it was really uplifting, then it let me down."},
        {Pun: "I knew a guy who collected candy canes, they were all in mint condition."},
        {Pun: "I was going to buy a book on phobias, but I was afraid it wouldn't help me."},
        {Pun: "The dead batteries were given out free of charge."},
        {Pun: "My fear of roses is a thorny issue. I'm not sure what it stems from, but it seems likely I'll be stuck with it."},
        {Pun: "When the cannibal showed up late to the luncheon, they gave him the cold shoulder."},
        {Pun: "I mixed up the cardiac resuscitation equipment with the lie detector, but I will de-fib you later."},
        {Pun: "Always trust a glue salesman. They tend to stick to their word."},
        {Pun: "Don't trust people that do acupuncture, they're back stabbers."},
        {Pun: "When a clock is hungry it goes back four seconds."},
        {Pun: "Whenever there is an earthquake the geologists are always quick to find fault."},
        {Pun: "I used to be addicted to soap, but I'm clean now."},
        {Pun: "What's the definition of a will? (It's a dead giveaway)."},
        {Pun: "Children who fail their coloring exams always need a shoulder to crayon."},
        {Pun: "If towels could tell jokes they would probably have a dry sense of humor."},
        {Pun: "Did you hear about the crime that happened in a parking garage? It was wrong on so many levels."},
        {Pun: "My new theory on inertia doesn't seem to be gaining momentum."},
        {Pun: "A hole has been found in the nudist camp wall. The police are looking into it."},
        {Pun: "Never discuss infinity with a mathematician, they can go on about it forever."},
        {Pun: "Smaller babies may be delivered by stork but the heavier ones need a crane."},
        {Pun: "Two peanuts were walking in a tough neighborhood and one of them was a-salted."},
        {Pun: "Some people's noses and feet are built backwards: their feet smell and their noses run."},
        {Pun: "My friend was fired from his job at the road department for stealing. I have to say I saw it coming. The last time I was at his house all the signs were there."},
        {Pun: "Why did the pig stop sunbathing? He was bacon in the heat."},
        {Pun: "If you lose your hearing, is it ear replaceable?"},
        {Pun: "Novice pirates make terrible singers because they can't hit the high seas."},
        {Pun: "Jill broke her finger today, but on the other hand she was completely fine."},
        {Pun: "Sleeping comes so naturally to me, I could do it with my eyes closed."},
        {Pun: "What is a thesaurus' favorite dessert? Synonym buns."},
        {Pun: "Pencils could be made with erasers at both ends, but what would be the point?"},
        {Pun: "Einstein developed a theory about space, and it was about time too."},
        {Pun: "My tailor is happy to make a pair of pants for me, or at least sew it seams."},
        {Pun: "I couldn't quite remember how to throw a boomerang, but eventually it came back to me."},
        {Pun: "Show me a piano falling down a mineshaft and I'll show you A-flat minor."},
        {Pun: "I wasn't originally going to get a brain transplant, but then I changed my mind."},
        {Pun: "I'd tell you a chemistry joke but I know I wouldn't get a reaction."},
        {Pun: "I wondered why the baseball was getting bigger. Then it hit me."},
        {Pun: "Yesterday I accidentally swallowed some food coloring. The doctor says I'm OK, but I feel like I've dyed a little inside."},
        {Pun: "A friend of mine tried to annoy me with bird puns, but I soon realized that toucan play at that game."}
      ]);
    });
};
